Repository Team-bbangbbangs/EduMate-Server, pull requests merged in 2025-06, with the labels that each got.

#4 [EDMT-84] 공통 응답 API 포맷 구현
  src/main/java/com/edumate/eduserver/common/ApiResponse.java
  src/main/java/com/edumate/eduserver/common/advice/GlobalExceptionHandler.java
  src/main/java/com/edumate/eduserver/common/advice/ResponseAdvice.java
  src/main/java/com/edumate/eduserver/common/code/CommonSuccessCode.java
  src/main/java/com/edumate/eduserver/common/code/ErrorCode.java
  src/main/java/com/edumate/eduserver/common/code/SuccessCode.java
  src/main/java/com/edumate/eduserver/common/exception/BadRequestException.java
  src/main/java/com/edumate/eduserver/common/exception/ConflictException.java
  src/main/java/com/edumate/eduserver/common/exception/EduMateCustomException.java
  src/main/java/com/edumate/eduserver/common/exception/ForbiddenException.java
  src/main/java/com/edumate/eduserver/common/exception/NotFoundException.java
  src/main/java/com/edumate/eduserver/common/exception/UnauthorizedException.java
Labels: ✨ feat

#5 [EDMT-78] CI/CD 워크플로우 및 도커 파일 설정
  .github/workflows/cd-dev.yml
  .gitignore
  Dockerfile-dev
  build.gradle
  docker-compose.dev.yml
Labels: 🔧 chore

#6 [EDMT-77] 테스트 커버리지 검증 및 Jacoco 리포트 자동 등록 설정
  .github/workflows/api-docs-page.yml
  .github/workflows/ci-pr-build-test.yml
  build.gradle
Labels: 🔧 chore

#11 [EDMT-93] 특정 학생의 생활기록부 작성 글을 생성 및 수정하는 기능 구현
  build.gradle
  src/main/java/com/edumate/eduserver/auth/exception/code/AuthErrorCode.java
  src/main/java/com/edumate/eduserver/common/ApiResponse.java
  src/main/java/com/edumate/eduserver/common/StudentRecordTypeConverter.java
  src/main/java/com/edumate/eduserver/common/advice/GlobalExceptionHandler.java
  src/main/java/com/edumate/eduserver/common/code/ErrorCode.java
  src/main/java/com/edumate/eduserver/common/exception/BadRequestException.java
  src/main/java/com/edumate/eduserver/common/exception/EduMateCustomException.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordCreateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordDetail.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/InvalidSemesterFormatException.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/MemberStudentRecordNotFoundException.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/RecordTypeNotFoundException.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/StudentRecordDetailNotFoundException.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/code/StudentRecordErrorCode.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/repository/MemberStudentRecordRepository.java
  src/main/java/com/edumate/eduserver/studentrecord/repository/StudentRecordDetailRepository.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/main/java/com/edumate/eduserver/user/domain/Member.java
  src/test/java/com/edumate/eduserver/common/StudentRecordTypeConverterTest.java
Labels: ✨ feat

#13 [EDMT-133] Test Fixture 생성 및 Test Base 클래스 생성
  src/main/java/com/edumate/eduserver/auth/domain/AuthorizationCode.java
  src/main/java/com/edumate/eduserver/auth/domain/ValidEmail.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/MemberStudentRecord.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordDetail.java
  src/main/java/com/edumate/eduserver/subject/domain/Subject.java
  src/main/java/com/edumate/eduserver/user/domain/NicknameBannedWord.java
  src/test/java/com/edumate/eduserver/util/ControllerTest.java
  src/test/java/com/edumate/eduserver/util/DbCleaner.java
  src/test/java/com/edumate/eduserver/util/RepositoryTest.java
  src/test/java/com/edumate/eduserver/util/ServiceTest.java
  src/test/java/com/edumate/eduserver/util/fixture/MemberFixture.java
  src/test/java/com/edumate/eduserver/util/fixture/MemberStudentRecordFixture.java
  src/test/java/com/edumate/eduserver/util/fixture/StudentRecordDetailFixture.java
  src/test/java/com/edumate/eduserver/util/fixture/SubjectFixture.java
Labels: ✅ test

#14 [EDMT-134] 생기부 종합 글 저장 기능 테스트 작성 및 RestDocs 반영
  build.gradle
  src/docs/asciidoc/api/studentRecord.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/edumate/eduserver/common/StudentRecordTypeConverter.java
  src/main/java/com/edumate/eduserver/common/advice/GlobalExceptionHandler.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordCreateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordDetail.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/InvalidRecordTypeException.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/repository/StudentRecordDetailRepository.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/test/java/com/edumate/eduserver/common/StudentRecordTypeConverterTest.java
  src/test/java/com/edumate/eduserver/docs/CustomRestDocsUtils.java
  src/test/java/com/edumate/eduserver/docs/RestDocsSupport.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
  src/test/java/com/edumate/eduserver/util/ControllerTest.java
  src/test/java/com/edumate/eduserver/util/ServiceTest.java
  src/test/java/com/edumate/eduserver/util/fixture/MemberFixture.java
  src/test/java/com/edumate/eduserver/util/fixture/MemberStudentRecordFixture.java
  src/test/java/com/edumate/eduserver/util/fixture/StudentRecordDetailFixture.java
  src/test/java/com/edumate/eduserver/util/fixture/SubjectFixture.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: ✅ test

#15 [EDMT-110] 특정 학생의 생기부 특정 항목 종합 글을 불러오는 API 구현
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/response/StudentRecordDetailResponse.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/main/java/com/edumate/eduserver/studentrecord/service/dto/StudentRecordDetailDto.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ✨ feat

#19 [EDMT-93] API 경로 변경으로 인한 로직 및 테스트코드 수정
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/common/ApiResponse.java
  src/main/java/com/edumate/eduserver/common/advice/GlobalExceptionHandler.java
  src/main/java/com/edumate/eduserver/common/code/BusinessErrorCode.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordCreateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/main/java/com/edumate/eduserver/studentrecord/service/dto/StudentRecordDetailDto.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ♻️ refactor

#23 [EDMT-144] 유저의 인증 코드를 검증하는 API 구현
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/studentRecord.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/domain/AuthorizationCode.java
  src/main/java/com/edumate/eduserver/auth/domain/AuthorizeStatus.java
  src/main/java/com/edumate/eduserver/auth/exception/AuthCodeNotFoundException.java
  src/main/java/com/edumate/eduserver/auth/exception/ExpiredCodeException.java
  src/main/java/com/edumate/eduserver/auth/exception/MisMatchedCodeException.java
  src/main/java/com/edumate/eduserver/auth/exception/code/AuthErrorCode.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/facade/response/EmailVerifyResponse.java
  src/main/java/com/edumate/eduserver/auth/repository/AuthorizationCodeRepository.java
  src/main/java/com/edumate/eduserver/auth/security/jwt/JwtGenerator.java
  src/main/java/com/edumate/eduserver/auth/service/AuthService.java
  src/main/java/com/edumate/eduserver/auth/service/EmailService.java
  src/main/java/com/edumate/eduserver/auth/service/RandomCodeGenerator.java
  src/main/java/com/edumate/eduserver/auth/service/Token.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/main/java/com/edumate/eduserver/user/domain/Member.java
  src/main/java/com/edumate/eduserver/user/service/MemberService.java
  src/test/java/com/edumate/eduserver/auth/controller/AuthControllerTest.java
  src/test/java/com/edumate/eduserver/auth/repository/AuthorizationCodeRepositoryTest.java
  src/test/java/com/edumate/eduserver/auth/service/RandomCodeGeneratorTest.java
  src/test/java/com/edumate/eduserver/util/RepositoryTest.java
Labels: ✨ feat, size/L

#30 [EDMT-153] 빌드 실패 오류 해결
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
Labels: 🚨 bug

#32 [EDMT-127] 학생 관리 페이지에서 학생 1명 추가하는 API를 구현한다.
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordCreateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/vo/StudentRecordCreateInfo.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ✨ feat

#33 [EDMT-125] 학생 관리 페이지에서 학생 1명 수정하는 API를 구현한다.
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordOverviewUpdateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/vo/StudentRecordUpdateInfo.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordDetail.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ✨ feat

#34 [EDMT-126] 학생 관리 페이지에서 학생 1명 수정하는 API를 구현한다.
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordDetail.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ✨ feat

#36 [EDMT-160] 로그인, 로그아웃, 토큰 재발급 API 구현
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/controller/request/MemberLoginRequest.java
  src/main/java/com/edumate/eduserver/auth/domain/AuthorizationCode.java
  src/main/java/com/edumate/eduserver/auth/exception/MismatchedPasswordException.java
  src/main/java/com/edumate/eduserver/auth/exception/code/AuthErrorCode.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/facade/response/MemberLoginResponse.java
  src/main/java/com/edumate/eduserver/auth/facade/response/MemberReissueResponse.java
  src/main/java/com/edumate/eduserver/auth/security/jwt/JwtParser.java
  src/main/java/com/edumate/eduserver/auth/security/jwt/JwtValidator.java
  src/main/java/com/edumate/eduserver/auth/service/AuthService.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/main/java/com/edumate/eduserver/member/exception/code/MemberErrorCode.java
  src/main/java/com/edumate/eduserver/member/repository/MemberRepository.java
  src/main/java/com/edumate/eduserver/member/service/MemberService.java
  src/test/java/com/edumate/eduserver/auth/facade/AuthFacadeTest.java
  src/test/java/com/edumate/eduserver/notice/controller/NoticeControllerTest.java
Labels: ✨ feat

#37 [EDMT-173] @MemberUUID를 @MemberId로 변경하고, 바로 ID를 매핑하도록 리팩토링
  build.gradle
  src/docs/asciidoc/api/auth.adoc
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/exception/MismatchedPasswordException.java
  src/main/java/com/edumate/eduserver/auth/exception/code/AuthErrorCode.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/security/jwt/JwtParser.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/main/java/com/edumate/eduserver/common/MemberIdArgumentResolver.java
  src/main/java/com/edumate/eduserver/common/annotation/MemberId.java
  src/main/java/com/edumate/eduserver/common/config/WebConfig.java
  src/main/java/com/edumate/eduserver/common/security/MemberAuthentication.java
  src/main/java/com/edumate/eduserver/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/edumate/eduserver/member/domain/Member.java
  src/main/java/com/edumate/eduserver/member/service/MemberAuthenticationService.java
  src/main/java/com/edumate/eduserver/member/service/MemberService.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/test/java/com/edumate/eduserver/auth/controller/AuthControllerTest.java
  src/test/java/com/edumate/eduserver/auth/facade/AuthFacadeTest.java
  src/test/java/com/edumate/eduserver/auth/service/TokenServiceTest.java
  src/test/java/com/edumate/eduserver/config/TestSecurityConfig.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/util/ControllerTest.java
Labels: ♻️ refactor

#38 [EDMT-186] 교사 인증 이메일 전송 API 구현
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/controller/request/EmailSendRequest.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/test/java/com/edumate/eduserver/auth/controller/AuthControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
Labels: ✨ feat

#41 [EDMT-174] 학기 추가 로직 구현
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/service/AuthService.java
  src/main/java/com/edumate/eduserver/member/domain/Member.java
  src/main/java/com/edumate/eduserver/member/repository/MemberRepository.java
  src/main/java/com/edumate/eduserver/member/service/MemberAuthenticationService.java
  src/main/java/com/edumate/eduserver/member/service/MemberService.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/SemesterCreateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/AlreadyExistingRecordException.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/code/StudentRecordErrorCode.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/test/java/com/edumate/eduserver/auth/controller/AuthControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
Labels: ✨ feat

#45 [EDMT-187] 학기 추가 API 삭제
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ♻️ refactor

#48 [EDMT-177] CORS 에러 해결
  src/main/java/com/edumate/eduserver/auth/jwt/JwtGenerator.java
  src/main/java/com/edumate/eduserver/auth/jwt/JwtParser.java
  src/main/java/com/edumate/eduserver/auth/jwt/JwtProperties.java
  src/main/java/com/edumate/eduserver/auth/jwt/JwtValidator.java
  src/main/java/com/edumate/eduserver/auth/jwt/TokenType.java
  src/main/java/com/edumate/eduserver/auth/jwt/config/JwtConfig.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/main/java/com/edumate/eduserver/common/config/SecurityConfig.java
  src/main/java/com/edumate/eduserver/common/security/filter/JwtAuthenticationFilter.java
  src/test/java/com/edumate/eduserver/auth/security/jwt/JwtGeneratorTest.java
  src/test/java/com/edumate/eduserver/auth/security/jwt/JwtValidatorTest.java
  src/test/java/com/edumate/eduserver/auth/service/TokenServiceTest.java
Labels: 🚨 bug

#49 [EDMT-191] 생활기록부 목록 조회 API 테스트 코드 추가
  src/docs/asciidoc/api/studentRecord.adoc
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
Labels: ✅ test

#52 [EDMT-105] Open AI 연동 및 생기부 생성 응답 기록 반환
  build.gradle
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/service/EmailEventListener.java
  src/main/java/com/edumate/eduserver/common/exception/TooManyRequestException.java
  src/main/java/com/edumate/eduserver/external/ai/ChatService.java
  src/main/java/com/edumate/eduserver/external/ai/config/ChatConfig.java
  src/main/java/com/edumate/eduserver/external/ai/exception/OpenAiQuotaExceededException.java
  src/main/java/com/edumate/eduserver/external/ai/exception/OpenAiRateLimitExceededException.java
  src/main/java/com/edumate/eduserver/external/ai/exception/OpenAiUnknownException.java
  src/main/java/com/edumate/eduserver/external/ai/exception/code/OpenAiErrorCode.java
  src/main/java/com/edumate/eduserver/external/aws/ses/EmailService.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordPromptRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordType.java
  src/main/java/com/edumate/eduserver/studentrecord/exception/InvalidRecordTypeException.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/response/StudentRecordAICreateResponse.java
  src/main/java/com/edumate/eduserver/studentrecord/service/PromptService.java
  src/test/java/com/edumate/eduserver/auth/facade/AuthFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
  src/test/resources/application-test.yml
Labels: ✨ feat

#53 [EDMT-105] 외부 네트워크와의 통신 과정 트랜잭션 범위에서 분리
  src/main/java/com/edumate/eduserver/external/ai/facade/ChatFacade.java
  src/main/java/com/edumate/eduserver/external/ai/facade/response/StudentRecordAICreateResponse.java
  src/main/java/com/edumate/eduserver/external/ai/service/ChatService.java
  src/main/java/com/edumate/eduserver/external/ai/service/PromptService.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/response/StudentRecordPromptResponse.java
  src/test/java/com/edumate/eduserver/studentrecord/controller/StudentRecordControllerTest.java
Labels: ♻️ refactor

#54 [EDMT-193] Refresh Token을 HttpOnly 쿠키로 전달하도록 변경
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/studentRecord.adoc
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/facade/response/MemberLoginResponse.java
  src/main/java/com/edumate/eduserver/auth/facade/response/MemberReissueResponse.java
  src/main/java/com/edumate/eduserver/auth/facade/response/MemberSignUpResponse.java
  src/main/java/com/edumate/eduserver/auth/service/Token.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/main/java/com/edumate/eduserver/member/service/MemberService.java
  src/test/java/com/edumate/eduserver/auth/controller/AuthControllerTest.java
  src/test/java/com/edumate/eduserver/auth/facade/AuthFacadeTest.java
  src/test/java/com/edumate/eduserver/auth/service/TokenServiceTest.java
Labels: ♻️ refactor

#58 [EDMT-] refreshToken 검증 시 Bearer 파싱 로직 제외
  src/main/java/com/edumate/eduserver/auth/exception/code/AuthErrorCode.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/test/java/com/edumate/eduserver/auth/service/TokenServiceTest.java
Labels: 🚨 bug

#59 [EDMT-131] 생활기록부 타입 ENUM value명 변경
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordType.java
  src/test/java/com/edumate/eduserver/auth/service/TokenServiceTest.java
  src/test/java/com/edumate/eduserver/common/StudentRecordTypeConverterTest.java
Labels: 🔧 chore

#60 [EDMT-211] 비밀번호 변경 전 이메일 주소 전송 API 구현
  src/docs/asciidoc/api/auth.adoc
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/controller/request/PasswordFindRequest.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/common/config/SecurityConfig.java
  src/main/java/com/edumate/eduserver/member/service/MemberService.java
  src/test/java/com/edumate/eduserver/auth/controller/AuthControllerTest.java
Labels: ✨ feat

#62 [EDMT-222] 공지사항 수정 및 삭제 API 구현
  src/docs/asciidoc/api/notice.adoc
  src/main/java/com/edumate/eduserver/auth/domain/AuthorizationCode.java
  src/main/java/com/edumate/eduserver/common/entity/BaseEntity.java
  src/main/java/com/edumate/eduserver/member/domain/Member.java
  src/main/java/com/edumate/eduserver/member/domain/NicknameBannedWord.java
  src/main/java/com/edumate/eduserver/notice/controller/AdminNoticeController.java
  src/main/java/com/edumate/eduserver/notice/controller/request/NoticeUpdateRequest.java
  src/main/java/com/edumate/eduserver/notice/domain/Notice.java
  src/main/java/com/edumate/eduserver/notice/facade/NoticeFacade.java
  src/main/java/com/edumate/eduserver/notice/service/NoticeService.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/RecordMetadata.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/RecordPrompt.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordDetail.java
  src/main/java/com/edumate/eduserver/subject/domain/Subject.java
  src/test/java/com/edumate/eduserver/notice/controller/AdminNoticeControllerTest.java
  src/test/java/com/edumate/eduserver/notice/facade/NoticeFacadeTest.java
  src/test/java/com/edumate/eduserver/notice/service/NoticeServiceTest.java
Labels: ✨ feat

#64 [EDMT-207] 생기부 작성 금지어를 필터링하기 위한 프롬프팅
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/external/ai/service/ChatService.java
  src/main/java/com/edumate/eduserver/external/ai/service/PromptService.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordsCreateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/vo/StudentRecordInfo.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/RecordPrompt.java
  src/main/java/com/edumate/eduserver/studentrecord/domain/StudentRecordType.java
Labels: ✨ feat

#66 [EDMT-196] 배포 전, 교육청 이메일 도메인 검증 주석 해제
  src/main/java/com/edumate/eduserver/auth/service/AuthService.java
Labels: 🔧 chore

#67 [EDMT-224] 로그인, 토큰 재발급 시 isAdmin 필드 추가
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/facade/response/MemberReissueResponse.java
  src/main/java/com/edumate/eduserver/auth/facade/response/MemberSignUpResponse.java
  src/main/java/com/edumate/eduserver/common/CookieHandler.java
  src/test/java/com/edumate/eduserver/auth/controller/AuthControllerTest.java
Labels: ♻️ refactor
