Repository Team-bbangbbangs/EduMate-Server, pull requests merged in 2025-07, with the labels that each got.

#70 [EDMT-233] MissingRequestCookieException을 전역 예외 처리기에 추가
  src/main/java/com/edumate/eduserver/auth/jwt/JwtValidator.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/main/java/com/edumate/eduserver/common/advice/GlobalExceptionHandler.java
  src/test/java/com/edumate/eduserver/auth/security/jwt/JwtValidatorTest.java
Labels: 🚨 bug

#71 [EDMT-254] 학기 정보가 생성 된 후에도 bulk 추가가 가능하도록 수정
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ♻️ refactor

#72 [EDMT-237] 마이페이지에서 비밀번호 변경 로직 추가
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/edumate/eduserver/member/controller/MemberController.java
  src/main/java/com/edumate/eduserver/member/controller/request/PasswordChangeRequest.java
  src/main/java/com/edumate/eduserver/member/exception/InvalidPasswordException.java
  src/main/java/com/edumate/eduserver/member/exception/PasswordSameAsOldException.java
  src/main/java/com/edumate/eduserver/member/exception/code/MemberErrorCode.java
  src/main/java/com/edumate/eduserver/member/facade/MemberFacade.java
  src/test/java/com/edumate/eduserver/member/controller/MemberControllerTest.java
Labels: ✨ feat

#74 [EDMT-240] logback 기반 로깅 시스템 도입 및 인증/외부시스템 연동 로그 체계화
  .gitignore
  docker-compose.dev.yml
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/common/advice/GlobalExceptionHandler.java
  src/main/java/com/edumate/eduserver/common/config/AsyncConfig.java
  src/main/java/com/edumate/eduserver/common/log/MdcLoggingFilter.java
  src/main/java/com/edumate/eduserver/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/edumate/eduserver/external/ai/service/ChatService.java
  src/main/java/com/edumate/eduserver/external/aws/mail/EmailService.java
  src/main/java/com/edumate/eduserver/external/aws/mail/event/EmailEventListener.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/resources/logback-spring.xml
Labels: 🔧 chore

#75 [EDMT-252] 유저 이메일 변경 API 구현
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/service/AuthService.java
  src/main/java/com/edumate/eduserver/external/aws/mail/AwsSesEmailMapper.java
  src/main/java/com/edumate/eduserver/external/aws/mail/EmailService.java
  src/main/java/com/edumate/eduserver/external/aws/mail/event/EmailEventListener.java
  src/main/java/com/edumate/eduserver/member/controller/MemberController.java
  src/main/java/com/edumate/eduserver/member/controller/request/MemberEmailUpdateRequest.java
  src/main/java/com/edumate/eduserver/member/domain/Member.java
  src/main/java/com/edumate/eduserver/member/facade/MemberFacade.java
  src/main/java/com/edumate/eduserver/member/facade/dto/MemberEmailUpdatedEvent.java
  src/main/java/com/edumate/eduserver/member/service/MemberService.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/main/resources/templates/update-email-verification.html
  src/test/java/com/edumate/eduserver/member/controller/MemberControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: ✨ feat

#77 [EDMT-239] promtail이 로그 파일을 정상 수집할 수 있도록 설정 개선
  docker-compose.dev.yml
Labels: 🚨 bug

#79 [EDMT-204] 프로메테우스 메트릭 수집 경로를 인증 필터 제외
  src/main/java/com/edumate/eduserver/common/config/SecurityConfig.java
Labels: 🚨 bug, ⚙️ infra

#81 [EDMT-256] Release v1.0.1
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .gitignore
  build.gradle
  docker-compose.dev.yml
  docker-compose.prod.yml
  promtail-config.yml
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/edumate/eduserver/auth/controller/AuthController.java
  src/main/java/com/edumate/eduserver/auth/facade/AuthFacade.java
  src/main/java/com/edumate/eduserver/auth/jwt/JwtValidator.java
  src/main/java/com/edumate/eduserver/auth/service/AuthService.java
  src/main/java/com/edumate/eduserver/auth/service/TokenService.java
  src/main/java/com/edumate/eduserver/common/advice/GlobalExceptionHandler.java
  src/main/java/com/edumate/eduserver/common/config/AsyncConfig.java
  src/main/java/com/edumate/eduserver/common/config/SecurityConfig.java
  src/main/java/com/edumate/eduserver/common/log/MdcLoggingFilter.java
  src/main/java/com/edumate/eduserver/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/edumate/eduserver/external/ai/service/ChatService.java
  src/main/java/com/edumate/eduserver/external/aws/mail/AwsSesEmailMapper.java
  src/main/java/com/edumate/eduserver/external/aws/mail/EmailService.java
  src/main/java/com/edumate/eduserver/external/aws/mail/event/EmailEventListener.java
  src/main/java/com/edumate/eduserver/member/controller/MemberController.java
  src/main/java/com/edumate/eduserver/member/controller/request/MemberEmailUpdateRequest.java
  src/main/java/com/edumate/eduserver/member/controller/request/MemberNicknameValidationRequest.java
  src/main/java/com/edumate/eduserver/member/controller/request/MemberProfileUpdateRequest.java
  src/main/java/com/edumate/eduserver/member/controller/request/PasswordChangeRequest.java
  src/main/java/com/edumate/eduserver/member/domain/Member.java
  src/main/java/com/edumate/eduserver/member/exception/InvalidPasswordException.java
  src/main/java/com/edumate/eduserver/member/exception/MemberNicknameDuplicateException.java
  src/main/java/com/edumate/eduserver/member/exception/MemberNicknameInvalidException.java
  src/main/java/com/edumate/eduserver/member/exception/PasswordSameAsOldException.java
  src/main/java/com/edumate/eduserver/member/exception/code/MemberErrorCode.java
  src/main/java/com/edumate/eduserver/member/facade/MemberFacade.java
  src/main/java/com/edumate/eduserver/member/facade/dto/MemberEmailUpdatedEvent.java
  src/main/java/com/edumate/eduserver/member/facade/response/MemberNicknameValidationResponse.java
  src/main/java/com/edumate/eduserver/member/repository/MemberRepository.java
  src/main/java/com/edumate/eduserver/member/repository/NicknameBannedWordRepository.java
  src/main/java/com/edumate/eduserver/member/service/MemberService.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/StudentRecordController.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/StudentRecordCreateRequest.java
  src/main/java/com/edumate/eduserver/studentrecord/controller/request/vo/StudentRecordCreateInfo.java
  src/main/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacade.java
  src/main/java/com/edumate/eduserver/studentrecord/service/StudentRecordService.java
  src/main/resources/logback-spring.xml
  src/main/resources/templates/update-email-verification.html
  src/test/java/com/edumate/eduserver/auth/security/jwt/JwtValidatorTest.java
  src/test/java/com/edumate/eduserver/member/controller/MemberControllerTest.java
  src/test/java/com/edumate/eduserver/studentrecord/facade/StudentRecordFacadeTest.java
  src/test/java/com/edumate/eduserver/studentrecord/service/StudentRecordServiceTest.java
Labels: Release

#82 [EDMT-249] 마이페이지 API restdocs 수정
  src/docs/asciidoc/api/member.adoc
Labels: 🚨 bug

#83 [EDMT-240] 로그 파일 압축
  promtail-config.yml
  src/main/resources/logback-spring.xml
Labels: ♻️ refactor
